version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.6.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis:5.0.7-buster
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      MONGO_INITDB_DATABASE: pp-core-menu-local
    ports:
      - "27017:27017"
    volumes:
      - ./docker-volume/mongodb:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge