package br.com.petshop.system.schedule.model.enums;

public enum ScheduleType {
    OWNER, //DONO DA EMPRESA
    MANAGER, //GERENTE/ADMINISTRADOR
    VETERINARIAN, //VETERINARIO
    VETERINARY_ASSISTANT, //ASSISTENTE DE VETERINARIO
    RECEPTIONIST, //RECEPCIONISTA
    BATHER, //BANHISTA
    GROOMER, //TOSADOR
    BEAUTICIAN, //ESTETICISTA
    SELLER; //VENDEDOR
}
